# Generated by Django 4.1.12 on 2023-10-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymenthistory',
            table='PaymentHistory',
        ),
    ]
